<link rel="stylesheet" href="style/style.css">
<section class="parallax">
	
	<img src="images/dom_leto_dizayn_gorod_ulica_714_1920x1080.jpg" alt="ALT">
</section>
<section>
	<div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non voluptate, corporis voluptatem accusamus nam. Deserunt dolore, repudiandae temporibus dolorum optio quod pariatur aperiam unde id reiciendis voluptatum repellendus voluptatibus. Sed.</div>
	<div>Illum blanditiis ullam unde nobis dicta dolore repudiandae enim ducimus tempore dolores eos similique tenetur laudantium, sunt, incidunt nisi voluptas consectetur, error est, dolor facilis ipsa magnam. Temporibus, expedita, asperiores.</div>
	<div>Unde itaque, esse quas possimus tempore est rerum repudiandae nesciunt dolorem ipsam hic ratione dicta inventore expedita quaerat pariatur quam distinctio, quibusdam. Ipsa iure corporis ratione nemo totam sed dignissimos.</div>
	<div>Cupiditate dignissimos dicta laudantium ipsa, minus aliquid, praesentium nostrum quisquam ipsum, quia delectus veniam sapiente accusantium maxime tempore. Velit voluptates ipsum enim atque impedit? Sed quae, iste numquam. Quas, iure.</div>
	<div>Non nostrum quis cumque, nam incidunt, eveniet et! Corrupti, vero, alias. Quibusdam, accusantium hic placeat animi aut cumque quaerat dolor aspernatur dolores, amet, quod, velit. Quod nisi, voluptatibus ut qui!</div>
	<div>Cupiditate officia explicabo fugiat ab ut maiores aut suscipit tenetur aperiam omnis ipsam deleniti numquam, rem voluptatem at accusamus quam. Nihil illo dolores quod quas odio officia tempore aliquid excepturi!</div>
	<div>Fugiat sit, totam temporibus molestiae non dolore facere id similique inventore illum nemo quam dolorem saepe deserunt debitis aperiam, facilis error quae. Maxime deserunt id molestias, reprehenderit officiis dignissimos tempora.</div>
	<div>Cumque libero omnis earum adipisci labore, non ducimus quae corporis nemo! Veritatis, similique at cumque. Similique beatae dolor id voluptatibus quas eius aspernatur, fuga nesciunt quia suscipit, omnis reiciendis dolorem.</div>
	<div>Molestias ullam laborum illum cum et asperiores consectetur sed architecto, explicabo non, neque accusantium dolor quos rerum dolore, impedit assumenda fugit debitis eum reiciendis unde! Itaque eum, sit soluta rerum.</div>
	<div>Incidunt quod iusto nulla, commodi, culpa deleniti placeat, ipsam ea, dolor iure autem quisquam harum mollitia. Repellendus ducimus vero ex repudiandae dolorem tenetur pariatur quo consequatur eligendi, voluptates, fuga asperiores.</div>
	<div>Officia possimus, saepe obcaecati, nostrum corrupti quaerat, magnam pariatur voluptatem dolor tenetur natus blanditiis assumenda? Voluptatum, error incidunt, tempora harum asperiores reiciendis ea omnis sapiente assumenda quisquam cumque possimus voluptatibus.</div>
	<div>Ab id laboriosam provident quaerat cumque dignissimos, expedita atque. Consectetur, nihil consequatur sit praesentium ad sapiente pariatur, sint, earum vero ipsa dolores ducimus est optio, quam aut officiis totam non?</div>
	<div>Mollitia quis numquam facere maxime corrupti laborum fugiat tenetur tempore, nemo aspernatur culpa a dolorum ipsum eligendi odit sint at optio, iusto quas dignissimos aperiam veniam magnam, voluptate voluptas nam.</div>
	<div>Asperiores soluta praesentium nobis facilis repellendus, necessitatibus maiores voluptas non sequi, consequatur fugiat quaerat eaque unde, amet perferendis veritatis? Similique aspernatur eaque, voluptatum ipsum voluptatem reiciendis eveniet nostrum. Nostrum, ab.</div>
	<div>Omnis, eveniet culpa quia, delectus quis facere minus dolorum dolore totam. Alias ex nemo similique quos dicta assumenda aperiam, quas tempore facilis adipisci, quae, magnam. Minus officiis, quae non dolorum.</div>
	<div>Quidem sapiente error magnam, similique non, autem natus fugit assumenda asperiores beatae adipisci exercitationem quasi reprehenderit, eum laudantium modi perspiciatis, deleniti iusto alias nesciunt ex quod officia enim! Ratione, accusantium!</div>
	<div>Laborum cumque eius, temporibus distinctio obcaecati quia labore aperiam rerum ipsa amet reprehenderit vitae, dolores deleniti consequuntur. Sapiente iure quam quidem veritatis voluptates debitis, libero hic aliquam itaque recusandae nam.</div>
	<div>Iusto delectus quasi voluptas eligendi impedit sunt nesciunt laboriosam eos sit, similique hic temporibus consectetur, dolorem nam fugit ad qui natus ex deleniti. Fugiat dignissimos facilis, est sed ea ipsum!</div>
	<div>Tempore at quia consectetur esse nobis vel quisquam dicta laborum, quas nulla ut provident! Ut saepe iusto reiciendis eaque consequatur iste minus nesciunt et cum dolorum adipisci, ab, modi sit.</div>
	<div>Perspiciatis eligendi doloribus unde, illum aliquam natus, molestiae! Eligendi impedit ad quam itaque obcaecati eaque accusantium perspiciatis maxime facilis, expedita, magni a repellendus mollitia assumenda excepturi labore quae illo dignissimos.</div>
	<div>Id, ipsum iusto possimus quisquam laudantium accusantium, quae vitae dolor quibusdam at accusamus, nulla earum sed ducimus pariatur officiis sapiente non, vel commodi similique deleniti beatae inventore quam! Earum, odio.</div>
	<div>Qui explicabo, sunt unde saepe temporibus, omnis et id molestias vitae, ipsam eveniet? Hic vero molestiae adipisci porro fugiat dicta minus fugit ullam eveniet quam ratione asperiores, ad aut incidunt.</div>
	<div>Blanditiis hic delectus rerum minus distinctio doloribus ea amet quas eum eligendi! Nisi quos facilis voluptate suscipit dolorem, ipsam laudantium ex laborum magnam, eius placeat rem natus quisquam, iure voluptatibus.</div>
	<div>Corrupti debitis repudiandae veritatis distinctio odit eius minus aliquid dicta totam, assumenda! Officiis odit, sapiente officia vitae corrupti. Laboriosam voluptas, minus, quasi numquam nam optio odio eveniet facere fuga. Excepturi.</div>
	<div>Error aspernatur, quos porro natus officia, nesciunt doloribus provident dolore minima eius quisquam aliquid tenetur eveniet. Sed, architecto, doloribus! Voluptatem necessitatibus totam quis deserunt, error perspiciatis sed porro temporibus dolorum.</div>
	<div>Quibusdam molestiae minima ea repellat deserunt saepe vitae amet natus porro nostrum eos odit obcaecati corrupti, voluptates officia cumque impedit, aliquid, fugit consequatur cupiditate doloremque vel aspernatur? Sed, nam, eius.</div>
	<div>Tenetur, nihil nisi iusto, modi dolores blanditiis atque architecto mollitia in laborum asperiores aut velit temporibus eveniet assumenda quos facilis suscipit est nesciunt veniam sapiente earum soluta fuga. Accusantium, quia.</div>
	<div>Ullam sint in sit dolore praesentium reiciendis adipisci id ex tempora, commodi, quae! Aspernatur voluptates officia distinctio consectetur, numquam pariatur harum vel molestias quibusdam rem tempora laboriosam maiores amet eaque.</div>
	<div>Est nobis sequi sunt ullam consectetur magnam odio ipsam fugit debitis suscipit perspiciatis veritatis culpa sapiente eveniet deleniti iusto tempore quia officia, repudiandae tenetur, accusantium magni quod provident. Veritatis, similique!</div>
	<div>Blanditiis sunt quaerat quisquam beatae sit unde saepe velit est veniam fugiat eveniet, voluptatum iure, atque ratione dolores provident nam. Unde ut dignissimos, minus natus ad maiores, ipsam ducimus debitis.</div>
	<div>Fugiat autem, accusamus voluptate necessitatibus laudantium at voluptatibus consequuntur voluptatum error voluptatem et eligendi, corrupti corporis quod, esse accusantium! Dolore fugit natus possimus a, assumenda commodi voluptates eligendi, nihil voluptatibus?</div>
	<div>Id voluptatum eum suscipit et praesentium fugiat dicta, excepturi quia molestias consequuntur voluptatibus, debitis, similique aspernatur mollitia molestiae eveniet ex quasi! Officia nobis quia est et cumque ea dolorum provident.</div>
	<div>Iste, non, deserunt. Illum veniam ratione ea, iure modi debitis. Earum eos animi aperiam esse voluptates corporis, libero deleniti sapiente corrupti molestias obcaecati nam, repellat ab dolorem, nisi. Repellat, corrupti!</div>
	<div>Quidem impedit explicabo nihil corporis placeat, a molestias sint dolore eaque eius, hic modi culpa libero necessitatibus voluptatem possimus iusto sapiente dolores assumenda tempore debitis similique dolorum. Nihil, mollitia, culpa.</div>
	<div>Architecto facilis in eveniet nisi ab id illum facere recusandae blanditiis sit qui dolor eligendi voluptatem tenetur voluptatum excepturi deleniti ut unde eum vel commodi, corporis sunt laboriosam. At, magni.</div>
	<div>Vero neque laudantium soluta unde ullam totam! Omnis aliquam perspiciatis cum perferendis vero nobis deserunt nihil vel, deleniti delectus dicta reprehenderit alias, voluptates quidem natus officia, ab sunt dolorem. Debitis!</div>
	<div>Voluptas cum repudiandae provident, voluptatibus totam veritatis fugit quis perspiciatis, eum pariatur quidem perferendis earum commodi quas quasi. Laudantium corrupti vel ipsum recusandae id consectetur, deleniti consequuntur facere voluptas dolores!</div>
	<div>Facere commodi nam mollitia maiores, non! Animi accusamus obcaecati distinctio ex sequi, enim, inventore totam deserunt consectetur vitae, reprehenderit quam ab optio architecto? Numquam ducimus id itaque alias necessitatibus explicabo.</div>
	<div>Eligendi impedit magni, laborum doloribus quia cupiditate, tempora dolorem ipsa perferendis eum, magnam commodi quam. Rerum suscipit nesciunt ex fugiat. Dolorum cum excepturi eum suscipit at reprehenderit consequatur. Voluptatum, nam!</div>
	<div>Quo quos provident consectetur ratione velit alias blanditiis at amet. Recusandae, deleniti, blanditiis? Magnam quis, deserunt ducimus consequuntur officia omnis iure delectus aliquid ex quasi veniam in dolorum excepturi ratione.</div>
	<div>Eos quae dolore impedit perferendis quia. Inventore quae soluta temporibus impedit, porro praesentium sunt doloremque modi, esse deleniti minima veniam aliquam, aliquid tenetur in consequatur voluptates, ad saepe nobis suscipit?</div>
	<div>Necessitatibus dicta veritatis magni exercitationem explicabo quam consectetur quibusdam nulla, ratione porro eligendi esse expedita perspiciatis aliquid ullam velit fugiat nesciunt facere ipsa, in, ea et excepturi soluta. Cum, debitis!</div>
	<div>Unde earum sit non sapiente animi. Dolorum vel expedita aut voluptatem? Esse neque quae excepturi harum, nihil tempora facilis, non corporis nemo. Tenetur earum dolore, nisi veniam nesciunt veritatis mollitia!</div>
	<div>Quibusdam animi non ratione debitis, aliquid quia veniam quas fuga delectus, velit aliquam sit hic reprehenderit praesentium adipisci consequatur blanditiis saepe id nostrum eos tenetur recusandae? Saepe beatae exercitationem, velit.</div>
	<div>Quae officia repudiandae delectus magni quia commodi. Tenetur soluta recusandae dicta quam, voluptatem sit quo error nemo molestias eos nulla eveniet nisi, earum iusto deserunt quibusdam fuga optio aut aperiam!</div>
	<div>Vero animi in provident soluta quisquam quod velit aspernatur laborum nam aperiam facere dolorem quos non libero at culpa ratione hic ad sed, dolor possimus deleniti nihil. Accusamus repellendus, molestias.</div>
	<div>Cupiditate possimus dolores reiciendis id minus neque earum, quas consequuntur omnis incidunt explicabo vitae fuga commodi et amet qui aspernatur alias! Harum suscipit exercitationem illo dolorum adipisci. Laboriosam, ex iusto!</div>
	<div>Similique vitae harum ipsam necessitatibus eaque cumque eveniet, rerum minus nobis quasi officia amet, ipsum molestias voluptate dolores numquam odio quaerat vel libero provident. Harum reprehenderit, deserunt illum! Iste, eaque.</div>
	<div>Distinctio accusamus laboriosam enim aliquid incidunt architecto placeat facilis minima aut dolorum, repellendus harum beatae fugiat fugit corrupti nam laudantium, recusandae. Quidem eum, voluptatum cumque ut suscipit fugit tenetur eos.</div>
	<div>Cupiditate alias nemo commodi debitis. Vero natus, veritatis nisi id unde sequi necessitatibus ipsum optio impedit earum, corporis aut illum distinctio nam? Vel id repellendus quod, neque beatae suscipit natus.</div>
</section>
<script src="bower_components/jquery/dist/jquery.js"></script>
<script src="js/main.js"></script>